[package]
name = "whair"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3.2"

[dev-dependencies]
codespan-reporting = "0.11.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
